In [16]:
import pandas as pd
html_file = pd.read_html("./2022_may.html")[0]
html_file

Empty DataFrame
Columns: [(date, 5-1, 5-2, 5-3, 5-4, 5-5, 5-6, 5-7, 5-8, 5-9, 5-10, 5-11, 5-12, 5-13, 5-14, 5-15, 5-16, 5-17, 5-18, 5-19, 5-20, 5-21, 5-22, 5-23, 5-24, 5-25, 5-26, 5-27, 5-28, 5-29, 5-30, 5-31), (food, 673, 522, 2780, 1069, 174, 3824, 3279, 2014, 1380, 815, 3264, 455, 1061, 2581, 2661, 1131, 2908, 939, 998, 662, 3722, 402, 1828, 347, 2563, 2263, 376, 1011, 3902, 1904, 3805), (clothes, 620, 2025, 506, 1819, 2243, 3607, 1007, 2175, 515, 1153, 2749, 1234, 1315, 943, 2261, 2759, 1027, 36, 1441, 1678, 264, 1549, 3820, 1886, 1699, 1152, 237, 249, 1609, 2714, 196), (vehicle, 1891, 139, 3112, 3386, 510, 2327, 1657, 394, 2919, 1841, 2539, 2009, 3495, 1252, 3779, 3151, 3339, 850, 3164, 715, 850, 3237, 3440, 375, 2496, 228, 3105, 3099, 245, 149, 3068), (sports, 668, 569, 1107, 2652, 2929, 1358, 2291, 65, 451, 120, 3480, 3194, 1396, 1007, 1391, 1885, 263, 2681, 295, 2048, 3534, 1988, 3954, 964, 892, 28, 3310, 1423, 2271, 2958, 1161), (loans, 766, 890, 2603, 724, 397, 596, 1639, 3357, 2233, 1613, 635, 1034, 2716, 573, 3061, 2576, 395, 3169, 1238, 225, 925, 2769, 293, 14, 2735, 3202, 2864, 2401, 821, 2218, 3283), (other, 3145, 2159, 1794, 2230, 970, 1354, 2703, 3260, 155, 3667, 2574, 947, 52, 2855, 852, 368, 3241, 3615, 277, 1676, 3010, 3862, 3948, 1213, 3257, 3812, 1897, 1510, 1753, 1839, 881)]
Index: []